#!/bin/bash

#############################################
# Script de cpy NAS                         #
# ------------------------------------------#
# Ce script sauvegadre tout les fichiers    #
# qui sont dans le répertoire $PATH_SAVE à  #
# l'exeption du répertoire $PATH_BACK_FILES.#
# Ce script sauvegarde aussi les bases de   #
# données MYSQL.                            #
#############################################

###################
# Ouverture Sc101 #
###################

sudo sc101

#############################################
# Definition des variables                  #
#############################################

# Nom du fichier de backup
NAME_FILES="savftp"

# Paramètres MYSQL
MYSQL_NAME="savsql"

# Dates
DATE_JOUR=`date +%y%m%d` # Date du jour
DATE_MOIS=`date +%y%m` # Date du jour
DATE_MOINS3=`date --date '7 days ago' +%y%m%d` # Date 7 jours avant, pour effacer les vieux backups


#############################################
# Sauvegarde sur le NAS                     #
#############################################
echo "Copies des Fichiers ADF vers le NAS"
echo "`date +%X` Debut du transfert NAS" 

DELETENAME=${DATE_MOINS3}"-"${NAME_FILES}".tar.gz"
DELETENAME2=${DATE_MOINS3}"-"${MYSQL_NAME}".tar.gz"

cp /home/srvadf/*.gz /media/sc101/srvadf




#############################################
# Bloquage des droits et purge              #
#############################################
echo "Suppression des fichiers temparaire"

echo "Suppression des fichiers d une semaine"
rm -f /home/srvadf/$DELETENAME
rm -f /home/srvadf/$DELETENAME2

#rm -f /home/srvadf/*.gz


#############################################
# Sauvegarde sur le NAS                     #
#############################################
echo "Copies des Fichiers ONPC vers le NAS"
echo "`date +%X` Debut du transfert NAS" 

DELETENAME=${DATE_MOINS3}"-"${NAME_FILES}".tar.gz"
DELETENAME2=${DATE_MOINS3}"-"${MYSQL_NAME}".tar.gz"

cp /home/srvonpc/*.gz /media/sc101/srvonpc




#############################################
# Bloquage des droits et purge              #
#############################################
echo "Suppression des fichiers temparaire"

echo "Suppression des fichiers d une semaine"
rm -f /home/srvonpc/$DELETENAME
rm -f /home/srvonpc/$DELETENAME2

#rm -f /home/srvonpc/*.gz






echo "************************************************************" 
echo "`date +%X` Fin du script de copy vers le nas                " 
echo "************************************************************" 

#############
# Fin sc101 #
#############
sc101 -u 1

echo 'FIN'
exit 0
