#!/bin/bash

#############################################
# Script de sauvegarde pour FTP             #
# ------------------------------------------#
# Ce script sauvegadre tout les fichiers    #
# qui sont dans le répertoire $PATH_SAVE à  #
# l'exeption du répertoire $PATH_BACK_FILES.#
# Ce script sauvegarde aussi les bases de   #
# données MYSQL.                            #
#############################################

#############################################
# Definition des variables                  #
#############################################

# Nom du fichier de backup
NAME_FILES="savftp"

# Paramètres MYSQL
MYSQL_USER="xavier"
MYSQL_PASS="matrix"
MYSQL_NAME="savsql"

# Dates
DATE_JOUR=`date +%y%m%d` # Date du jour
DATE_MOIS=`date +%y%m` # Date du jour
DATE_MOINS3=`date --date '7 days ago' +%y%m%d` # Date 7 jours avant, pour effacer les vieux backups

# Chemin des répertoires
PATH_SAVE="/var/www/adf" # Répertoire qui sera sauvegardé
PATH_BACK="/home/backup" # Répertoire de base des sauvegardes
PATH_BACK_FILES=${PATH_BACK}"/backupfiles" # Répertoire du backup des fichiers
PATH_BACK_LOGS=${PATH_BACK}"/logsfiles" # Répertoire pour les logs des backups
PATH_BACK_CONF=${PATH_BACK}"/configfiles" # Répertoire de sauvegarde des configurations
PATH_BACK_MYSQL=${PATH_BACK}"/mysqlfiles" # Répertoire de sauvegarde des configurations

PATH_APACHE="/etc/apache2" # Répertoire de configuration d'apache
PATH_MYSQL="/etc/mysql" # Répertoire de configuration de MYSQL
PATH_PHP="/etc/php5" # Répertoire de configuration de PHP
PATH_PROFTPD="/etc/proftpd" # Répertoire de configuration de proftpd
PATH_PHPMY="/etc/phpmyadmin" # Répertoire de configuration de phpmyadmin



#############################################
# Configuration des répertoires             #
#############################################



# Préparation du répertoire pour les logs
LOGNAME=${DATE_JOUR}"-backuplog.txt"
LOGFILE=${PATH_BACK_LOGS}"/"${LOGNAME}

if [ -d ${PATH_BACK_LOGS} ]; then 
	echo "`date +%X` répertoire [${PATH_BACK_LOGS}] existe" >> $LOGFILE
else 
	mkdir $PATH_BACK_LOGS
	echo "`date +%X` répertoire [${PATH_BACK_LOGS}] créé" >> $LOGFILE
fi





#############################################
# Bloquage des droits et purge              #
#############################################
echo "Suppression des fichiers "
echo "`date +%X` rm -f $PATH_BACK_FILES" >> $LOGFILE

rm -f $PATH_BACK_FILES/*.gz


echo "`date +%X` rm -f $PATH_BACK_FILES/$DELETENAME2" >> $LOGFILE
rm -f $PATH_BACK_MYSQL/*.sql


echo "************************************************************" >> $LOGFILE
echo "`date +%X` Fin du script de suppression                      " >> $LOGFILE
echo "************************************************************" >> $LOGFILE
echo "" >> $LOGFILE
echo "" >> $LOGFILE
echo 'FIN'
exit 0
